"""Tests for the single-variable isolation gate (tools/validate_pair.py)."""

import copy
import json
from pathlib import Path

import pytest

from validate_pair import flatten, stimulus_diff, validate_pair

ROOT = Path(__file__).resolve().parent.parent
PAIR_DIR = ROOT / "spec" / "pairs" / "ceiling_height_study_01"


@pytest.fixture(scope="module")
def schema():
    return json.loads((ROOT / "spec" / "room_spec.schema.json").read_text(encoding="utf-8"))


@pytest.fixture()
def control():
    return json.loads((PAIR_DIR / "control.spec.json").read_text(encoding="utf-8"))


@pytest.fixture()
def treatment():
    return json.loads((PAIR_DIR / "treatment.spec.json").read_text(encoding="utf-8"))


def codes(result):
    return [v["code"] for v in result["violations"]]


def test_checked_in_pair_passes(control, treatment, schema):
    result = validate_pair(control, treatment, schema)
    assert result["ok"], result["violations"]
    assert list(result["diff"]) == ["shell.ceiling_height_m"]
    assert result["diff"]["shell.ceiling_height_m"] == [3.2, 2.6]


def test_ceiling_height_coupling_is_reported(control, treatment, schema):
    result = validate_pair(control, treatment, schema)
    assert any("room volume" in note for note in result["notes"])


def test_undeclared_change_is_a_confound(control, treatment, schema):
    treatment = copy.deepcopy(treatment)
    treatment["lighting"]["intensity"] = 1.4  # sneaky second manipulation
    result = validate_pair(control, treatment, schema)
    assert not result["ok"]
    assert codes(result) == ["undeclared_change"]
    assert result["violations"][0]["path"] == "lighting.intensity"


def test_declared_but_unchanged_variable_fails(control, treatment, schema):
    treatment = copy.deepcopy(treatment)
    treatment["shell"]["ceiling_height_m"] = control["shell"]["ceiling_height_m"]
    result = validate_pair(control, treatment, schema)
    assert not result["ok"]
    assert "declared_unchanged" in codes(result)


def test_pair_id_mismatch(control, treatment, schema):
    treatment = copy.deepcopy(treatment)
    treatment["experiment"]["pair_id"] = "some_other_study"
    result = validate_pair(control, treatment, schema)
    assert not result["ok"]
    assert "pair_id_mismatch" in codes(result)


def test_two_controls_are_not_a_pair(control, treatment, schema):
    treatment = copy.deepcopy(treatment)
    treatment["experiment"]["condition"] = "control"
    result = validate_pair(control, treatment, schema)
    assert not result["ok"]
    assert "condition_invalid" in codes(result)


def test_schema_invalid_spec_is_rejected_before_diffing(control, treatment, schema):
    treatment = copy.deepcopy(treatment)
    treatment["surfaces"]["wall"]["material"] = "lava"  # not in the material enum
    result = validate_pair(control, treatment, schema)
    assert not result["ok"]
    assert codes(result) == ["schema_invalid"]


def test_provenance_differences_are_not_stimulus_changes(control, treatment, schema):
    treatment = copy.deepcopy(treatment)
    treatment["provenance"]["generated_by"] = "ai_agent"
    treatment["provenance"]["notes"] = "regenerated by the agent"
    result = validate_pair(control, treatment, schema)
    assert result["ok"], result["violations"]


def test_declared_parent_path_covers_nested_changes(control, treatment, schema):
    control, treatment = copy.deepcopy(control), copy.deepcopy(treatment)
    treatment["shell"]["ceiling_height_m"] = control["shell"]["ceiling_height_m"]
    for spec in (control, treatment):
        spec["experiment"]["manipulated_variables"] = ["furniture"]
    treatment["furniture"] = treatment["furniture"][:-1]  # drop the pendant light
    result = validate_pair(control, treatment, schema)
    assert result["ok"], result["violations"]


def test_flatten_uses_dotted_and_indexed_paths():
    flat = flatten({"a": {"b": 1}, "c": [{"d": 2}, 3]})
    assert flat == {"a.b": 1, "c[0].d": 2, "c[1]": 3}


def test_stimulus_diff_catches_missing_keys(control, treatment):
    treatment = copy.deepcopy(treatment)
    del treatment["openings"]["windows"][1]
    diff = stimulus_diff(control, treatment)
    assert any(path.startswith("openings.windows[1]") for path in diff)
