using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace RoomGen.Gate
{
    /// <summary>
    /// The single-variable isolation gate — a faithful C# port of Diego's reference implementation
    /// tools/validate_pair.py. A control/treatment pair of CANONICAL RoomSpecs (the frozen team
    /// contract, spec/room_spec.schema.json) is accepted only if the two specs differ in EXACTLY the
    /// declared manipulated_variables: nothing more, nothing less. This runs on the canonical spec
    /// BEFORE RoomSpecAdapter — it gates the experiment design, not the generator's internal form.
    ///
    /// Parity is enforced by PairGateTests, which replays spec/fixtures/diff_vectors.json (the golden
    /// vectors generated by the Python validator) and requires every case's expected block to match.
    ///
    /// Violation codes (identical to the Python): schema_invalid, missing_experiment, pair_id_mismatch,
    /// condition_invalid, declared_mismatch, undeclared_change, declared_unchanged.
    /// </summary>
    public static class PairGate
    {
        // Fields allowed/required to differ within a pair: experiment metadata and file history, not
        // the stimulus a participant sees.
        static readonly string[] NonStimulusPrefixes = { "experiment", "provenance" };

        // Guardrail #2's coupled-variable documentation, executable: changing the key inevitably
        // changes the listed properties too. Reported as NOTES, not violations — the researcher must
        // account for them; the gate cannot decouple them.
        static readonly IReadOnlyDictionary<string, string> CoupledVars = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "shell.ceiling_height_m", "also changes room volume and the window-to-wall ratio" },
            { "shell.contour",          "also changes floor area near corners and total wall arc length" },
            { "shell.width_m",          "also changes room volume and aspect ratio" },
            { "shell.length_m",         "also changes room volume and aspect ratio" },
            { "lighting.warmth",        "perceived brightness shifts with color temperature" },
            { "lighting.intensity",     "shadow depth and apparent texture contrast shift with brightness" },
        };

        public sealed class Violation
        {
            public string Code;
            public string Path;
            public string Message;
            public Violation(string code, string path, string message) { Code = code; Path = path; Message = message; }
        }

        public sealed class Result
        {
            public bool Ok;
            public readonly List<Violation> Violations = new List<Violation>();
            public readonly List<string> DiffPaths = new List<string>();   // sorted stimulus-diff keys
            public readonly List<string> Notes = new List<string>();

            /// <summary>Sorted, de-duplicated codes — the field the golden vectors compare.</summary>
            public List<string> ViolationCodes =>
                Violations.Select(v => v.Code).Distinct(StringComparer.Ordinal)
                          .OrderBy(c => c, StringComparer.Ordinal).ToList();

            public int NotesCount => Notes.Count;
        }

        // Distinct name (not an overload of the JObject entry): callers in assemblies that don't
        // reference Newtonsoft — e.g. the EditMode test assembly — can invoke this without the
        // compiler needing to resolve the JObject overload (which would require that reference).
        public static Result ValidateJson(string canonicalJsonA, string canonicalJsonB, string schemaJson) =>
            Validate(JObject.Parse(canonicalJsonA), JObject.Parse(canonicalJsonB), JObject.Parse(schemaJson));

        public static Result Validate(JObject specA, JObject specB, JObject schema)
        {
            var result = new Result();

            // 1. Schema. If either spec is schema-invalid, stop before diffing (matches Python).
            foreach (var (label, spec) in new[] { ("spec_a", specA), ("spec_b", specB) })
                foreach (var err in JsonSchemaLite.Validate(spec, schema))
                    result.Violations.Add(new Violation("schema_invalid", $"{label}:{err.Path}", err.Message));
            if (result.Violations.Count > 0) return Finish(result);

            // 2. Experiment blocks must carry the fields a pair needs.
            var expA = specA["experiment"] as JObject ?? new JObject();
            var expB = specB["experiment"] as JObject ?? new JObject();
            foreach (var (label, exp) in new[] { ("spec_a", expA), ("spec_b", expB) })
                foreach (var field in new[] { "condition", "manipulated_variables", "pair_id" })
                    if (exp[field] == null)
                        result.Violations.Add(new Violation("missing_experiment",
                            $"{label}:experiment.{field}", $"a pair spec must declare experiment.{field}"));
            if (result.Violations.Count > 0) return Finish(result);

            // 3. Shared pair_id (added, not fatal — the diff is still reported).
            var pairIdA = (string)expA["pair_id"];
            var pairIdB = (string)expB["pair_id"];
            if (!string.Equals(pairIdA, pairIdB, StringComparison.Ordinal))
                result.Violations.Add(new Violation("pair_id_mismatch", "experiment.pair_id",
                    $"'{pairIdA}' vs '{pairIdB}' — these specs are not a pair"));

            // 4. Exactly one control + one treatment.
            var conditions = new HashSet<string>(StringComparer.Ordinal)
                { (string)expA["condition"], (string)expB["condition"] };
            if (!conditions.SetEquals(new[] { "control", "treatment" }))
                result.Violations.Add(new Violation("condition_invalid", "experiment.condition",
                    $"pair must be exactly one control + one treatment, got [{string.Join(", ", conditions.OrderBy(c => c, StringComparer.Ordinal))}]"));

            // 5. Identical manipulated_variables lists. If they disagree, stop (matches Python).
            var declaredA = StringList(expA["manipulated_variables"]);
            var declaredB = StringList(expB["manipulated_variables"]);
            if (!declaredA.OrderBy(s => s, StringComparer.Ordinal)
                          .SequenceEqual(declaredB.OrderBy(s => s, StringComparer.Ordinal), StringComparer.Ordinal))
            {
                result.Violations.Add(new Violation("declared_mismatch", "experiment.manipulated_variables",
                    $"[{string.Join(", ", declaredA)}] vs [{string.Join(", ", declaredB)}]"));
                return Finish(result);
            }

            var declared = declaredA; // spec_a's list, original order (matches Python)

            // 6. The stimulus diff must be covered by the declared variables, and every declared
            //    variable must actually differ.
            var diff = StimulusDiff(specA, specB);
            result.DiffPaths.AddRange(diff.Keys); // already sorted (ordinal)

            foreach (var path in diff.Keys)
                if (!IsCovered(path, declared))
                    result.Violations.Add(new Violation("undeclared_change", path,
                        $"differs ({Show(diff[path].a)} vs {Show(diff[path].b)}) but is not in manipulated_variables — the pair is confounded"));

            foreach (var variable in declared)
                if (!diff.Keys.Any(path => IsCovered(path, new[] { variable })))
                    result.Violations.Add(new Violation("declared_unchanged", variable,
                        "declared as manipulated but identical in both specs"));

            // 7. Coupled-variable notes (from the declared list, whether or not it changed).
            foreach (var variable in declared)
                if (CoupledVars.TryGetValue(variable, out var description))
                    result.Notes.Add($"coupled: {variable} {description}");

            return Finish(result);
        }

        static Result Finish(Result r)
        {
            r.Ok = r.Violations.Count == 0;
            return r;
        }

        // ---- diff machinery (faithful to validate_pair.flatten / stimulus_diff / _is_covered) ----

        static readonly StringComparer Ord = StringComparer.Ordinal;

        static SortedDictionary<string, (JToken a, JToken b)> StimulusDiff(JObject specA, JObject specB)
        {
            var flatA = new Dictionary<string, JToken>(Ord); Flatten(specA, "", flatA);
            var flatB = new Dictionary<string, JToken>(Ord); Flatten(specB, "", flatB);

            var diff = new SortedDictionary<string, (JToken, JToken)>(Ord);
            var allPaths = new SortedSet<string>(Ord);
            allPaths.UnionWith(flatA.Keys);
            allPaths.UnionWith(flatB.Keys);

            foreach (var path in allPaths)
            {
                var firstSegment = path.Split('.')[0].Split('[')[0];
                if (Array.IndexOf(NonStimulusPrefixes, firstSegment) >= 0) continue;

                var hasA = flatA.TryGetValue(path, out var a);
                var hasB = flatB.TryGetValue(path, out var b);
                if (hasA != hasB || !JToken.DeepEquals(a, b))
                    diff[path] = (hasA ? a : null, hasB ? b : null);
            }
            return diff;
        }

        static void Flatten(JToken node, string prefix, Dictionary<string, JToken> output)
        {
            if (node is JObject obj)
            {
                foreach (var member in obj.Properties())
                    Flatten(member.Value, prefix.Length == 0 ? member.Name : prefix + "." + member.Name, output);
            }
            else if (node is JArray arr)
            {
                for (var i = 0; i < arr.Count; i++)
                    Flatten(arr[i], prefix + "[" + i + "]", output);
            }
            else
            {
                output[prefix] = node; // leaf (JValue, incl. null)
            }
        }

        static bool IsCovered(string path, IEnumerable<string> declared) =>
            declared.Any(v => path == v
                || path.StartsWith(v + ".", StringComparison.Ordinal)
                || path.StartsWith(v + "[", StringComparison.Ordinal));

        static List<string> StringList(JToken token) =>
            token is JArray arr ? arr.Select(t => (string)t).ToList() : new List<string>();

        static string Show(JToken t) => t == null ? "null" : t.ToString(Newtonsoft.Json.Formatting.None);
    }
}
